import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";
import Link from "next/link";

export default function ProductDetailPage() {
  const router = useRouter();
  const productId = router.query.productId;
  return (
    <div>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-4 ml-8">
        <Link href="/product">
          <a>Go back Product page</a>
        </Link>
        <h1 className="text-3xl">Product Detail Page of id {productId}</h1>
      </div>
    </div>
  );
}
