import Head from "next/head";
import React from "react";
import { useRouter } from "next/router";

export default function ProductDetailPage() {
  const router = useRouter();
  const productId = router.query.productId;
  const reviewId = router.query.reviewId;
  return (
    <div>
      <Head>
        <title>Review Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-4 ml-8">
        <h1 className="text-3xl">
          Review {reviewId} for product id {productId}
        </h1>
      </div>
    </div>
  );
}
