import Head from "next/head";
import React from "react";

export default function SweaterDetailPage() {
  return (
    <div>
      <Head>
        <title>Sweater Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-4 ml-8">
        <h1 className="text-3xl">Landing page for sweater</h1>
      </div>
    </div>
  );
}
