import Head from "next/head";

export default function FirstBlogPage() {
  return (
    <>
      <Head>
        <title>First Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-4 ml-8">
        <h1 className="text-3xl">First Blog Page</h1>
      </div>
    </>
  );
}
