import Head from "next/head";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-4 ml-8">
        <h1 className="text-3xl">Hello from about</h1>
      </div>
    </>
  );
}
